### ISSUE TITLE
FR: Ability to link another account to view the dashboard

### ISSUE THREAD

**Issue by wackywavytube** [felixbrucker/chia-dashboard-satellite#26] opened 2021-05-12 23:37 UTC
**Is your feature request related to a problem? Please describe.**
I used Google to link my account but I can't share my Google login with my fellow chia watcher. It would be nice to assign a guest account to allow them to view the dashboard. 

Or make a guest view key so they don't have to login.

**Comment by felixbrucker** [comment] 2021-05-13 06:33
Duplicate of #15

**Closed by felixbrucker** 2021-05-13 06:33 UTC
Labels: enhancement
